config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :cards, only: [:new, :create, :edit, :update, :destroy]
  get 'cards', action: :cards, controller: 'home'
  get 'invoices', action: :invoices, controller: 'home'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  has_many :invoices

  enum bank: [ :itau, :santander, :bradesco, :nubank, :caixa_economica, :banco_do_brasil ]

  validates :name, presence: true
  validates :bank, presence: true


end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  belongs_to :card, optional: true

  enum category: [ :luz, :telefone, :agua, :internet, :alimentacao, :fatura, :vestimenta, :outros]

  validates :name, presence: true
  validates :category, presence: true
  validates :value, presence: true
  validates :due_date, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :trackable

  has_person_name

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :age, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 18 }

  has_many :cards
  has_many :invoices

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:new, :edit]

  def new; end

  def edit; end

  def create
    @card = current_user.cards.new(card_params)

    if @card.save
      redirect_to cards_path, notice: 'Cartão adicionado com Sucesso'
    else
      render :new
    end
  end

  private

  def set_card
    @card = if params[:id]
              Card.find params[:id]
            else
              Card.new
            end
  end

  def card_params
    params.require(:card).permit(:name, :bank, :user_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index; end

  def cards; end

  def invoices; end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "erro impediu", "erros impediram") %> este cartão de ser salvo:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Primeiro Nome' %>
  </div>

  <div class="form-group">
    <%= form.select :bank, Card.banks.map { |key, value| [key.humanize, key] }, {}, class: 'form-control' %>
  </div>

  <div class="actions">
    <% if params[:id] %>
      <%= form.submit 'Salvar', class: 'btn btn-outline-success' %>
      <%= link_to 'Mostrar', @user, class: 'btn btn-outline-primary' %>
    <% else %>
      <%= form.submit 'Adicionar', class: 'btn btn-outline-success' %>
    <% end %>
    <%= link_to 'Voltar', cards_path, class: 'btn btn-outline-secondary' %>

  </div>

<% end %>

app/views/cards/edit.html.erb
<h1>Editar Cartão</h1>

<%= render 'form', card: @card %>

app/views/cards/new.html.erb
<h1>Adicionar Cartão</h1>

<%= render 'form', card: @card %>

app/views/home/cards.html.erb
<div class="row">
  <div class="col text-center">
    <h1>Cartões de <%= current_user.name %></h1>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        Todos
      </div>
      <% current_user.cards.each do |card| %>
        <div class="card-body">
          <h5 class="card-title"><%= card.name %></h5>
          <p class="card-text"><%= card.bank %></p>
          <%= link_to 'Editar Cartão', edit_card_path(card), class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class="card-footer text-muted">
        <%= link_to 'Adicionar Novo Cartão', new_card_path %>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        Em Aberto
      </div>
      <div class="card-body">
        <h5 class="card-title">Título especial</h5>
        <p class="card-text">Com suporte a texto embaixo, que funciona como uma introdução a um conteúdo adicional.</p>
        <a href="#" class="btn btn-primary">Visitar</a>
      </div>
      <div class="card-footer text-muted">
        <%= link_to 'Registrar Pagamento'%>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        Em Atraso
      </div>
      <div class="card-body">
        <h5 class="card-title">Título especial</h5>
        <p class="card-text">Com suporte a texto embaixo, que funciona como uma introdução a um conteúdo adicional.</p>
        <a href="#" class="btn btn-primary">Visitar</a>
      </div>
      <div class="card-footer text-muted">
        <%= link_to 'Registrar Pagamento'%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBills</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class='container'>
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="sticky-footer">
  <p>Criado em colaboração pelos hackers.</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="nav nav-pills flex-column flex-sm-row">
  <%= link_to 'Home', root_path, class: 'flex-sm-fill text-sm-center nav-link'%>
  <% if current_user %>
    <%= link_to 'Contas', invoices_path, class: 'flex-sm-fill text-sm-center nav-link' %>
    <%= link_to 'Cartões', cards_path, class: 'flex-sm-fill text-sm-center nav-link' %>
    <%= link_to 'Configurações', edit_user_registration_path, class: 'flex-sm-fill text-sm-center nav-link' %>
    <%= link_to 'Sair', destroy_user_session_path, method: 'delete', class: 'flex-sm-fill text-sm-center nav-link' %>
  <% else %>
    <a class="flex-sm-fill text-sm-center nav-link" href='<%= new_user_session_path %>'>Login</a>
    <a class="flex-sm-fill text-sm-center nav-link" href='<%= new_user_registration_path %>'>Cadastre-se</a>
  <% end %>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :first_name, class: 'form-control', placeholder: 'Primeiro Nome' %>
  </div>

  <div class="form-group">
    <%= form.text_field :last_name, class: 'form-control', placeholder: 'Sobrenome' %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class: 'form-control', placeholder: 'E-mail' %>
  </div>

  <div class="form-group">
    <%= form.number_field :age, class: 'form-control', placeholder: 'Idade' %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', class: 'btn btn-outline-success' %>
    <% if params[:id] %>
      <%= link_to 'Mostrar', @user, class: 'btn btn-outline-primary' %>
    <% end%>
    <%= link_to 'Voltar', users_path, class: 'btn btn-outline-secondary' %>

  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>